### ISSUE TITLE
LpSolve is not working on older Mac OS versions

### ISSUE THREAD

**Issue by joosbuijs** [rapidprom/rapidprom-source#43] opened 2016-11-30 07:13 UTC
As reported by a student to Alfredo.

Please include this in a 4.0.2. release quickly (deadline assignment 1 is Sunday Dec. 4)

**Comment by s-j-v-zelst** [comment] 2016-11-30 08:57
duplicate of issue #41

**Closed as completed** 2016-11-30 08:57 UTC
